import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './components/header/header';
import Footer from './components/footer/footer';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';
import { connectDB } from '@/util/database';
import AuthProvider from './components/provider/authProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  let userData = null;
  if (session) {
    let db = (await connectDB).db('homecook');
    let data = await db.collection('users').findOne({
      email: session.user.email,
    });
    if (data) {
      data._id = data._id.toString();
      userData = data;
    }
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header userData={userData} />
        <AuthProvider userData={userData}>{children}</AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
